import { useCallback, useEffect, useMemo, useState } from "react";
import { Navigate, NavLink, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownLeft, ArrowRight, ArrowUpRight, CalendarDays, CheckCircle2, CircleDollarSign, Database, Home, Menu, Pencil, Plus, RefreshCw, Settings, Trash2, User, WalletCards, X } from "lucide-react";
import { api, errorMessage } from "./services/api";
import type { AppUser, Transaction, TransactionInput } from "./types";
import { dateBR, money } from "./utils/format";

const PROFILE = "Paulo";
const transactionSchema = z.object({userId:z.string().trim().min(1,"Selecione o usuário"),date:z.string().min(1,"Informe a data"),description:z.string().trim().min(2,"Informe o título"),value:z.coerce.number().positive("Informe um valor válido"),recurring:z.boolean(),observation:z.string().max(500).optional(),category:z.string(),paymentMethod:z.string(),status:z.enum(["paid","pending","cancelled"]),type:z.enum(["income","expense"])});
type Toast={message:string;error?:boolean};

export default function App(){const[toast,setToast]=useState<Toast>();const notify=(message:string,error=false)=>{setToast({message,error});setTimeout(()=>setToast(undefined),3200)};return <><Routes><Route element={<Layout/>}><Route index element={<Dashboard/>}/><Route path="dashboard" element={<Navigate to="/" replace/>}/><Route path="usuarios" element={<Users notify={notify}/>}/><Route path="ganhos" element={<Movements type="income" notify={notify}/>}/><Route path="despesas" element={<Movements type="expense" notify={notify}/>}/><Route path="ganhos/novo" element={<MovementForm type="income" notify={notify}/>}/><Route path="despesas/nova" element={<MovementForm type="expense" notify={notify}/>}/><Route path="movimentacoes/:id" element={<MovementForm notify={notify}/>}/><Route path="configuracoes" element={<Configuration notify={notify}/>} /></Route></Routes>{toast&&<div className={`toast ${toast.error?"error":""}`}>{toast.message}</div>}</>}

function Layout(){const[open,setOpen]=useState(false);return <div className="shell"><aside className={open?"open":""}><div className="brand"><span>FB</span><div><b>Finanbase</b><small>Finance</small></div><button onClick={()=>setOpen(false)}><X/></button></div><nav><NavLink to="/" end><Home/>Dashboard</NavLink><NavLink to="/usuarios"><User/>Usuários</NavLink><NavLink to="/ganhos"><ArrowUpRight/>Ganhos</NavLink><NavLink to="/despesas"><ArrowDownLeft/>Despesas</NavLink><NavLink to="/configuracoes"><Settings/>Configurações</NavLink></nav><div className="user-card"><span>P</span><div><b>{PROFILE}</b><small>Perfil principal</small></div></div></aside><div className="content"><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><b>Olá, {PROFILE} 👋</b><small>Aqui está seu resumo financeiro de hoje.</small></div><NavLink to="/despesas/nova" className="primary"><Plus/>Nova movimentação</NavLink></header><main><Outlet/></main></div>{open&&<div className="backdrop" onClick={()=>setOpen(false)}/>}</div>}

function useLoad<T>(url:string,initial:T){const[data,setData]=useState(initial),[loading,setLoading]=useState(true),[error,setError]=useState("");const reload=useCallback(()=>{setLoading(true);setError("");api.get<T>(url).then(r=>setData(r.data)).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[url]);useEffect(reload,[reload]);return{data,loading,error,reload}}

function Dashboard(){const summary=useLoad("/dashboard/summary",{balance:0,income:0,expense:0,pending:0,count:0});const charts=useLoad<{monthly:{name:string;income:number;expense:number}[];evolution:{date:string;balance:number}[]}>("/dashboard/charts",{monthly:[],evolution:[]});const recent=useLoad<{data:Transaction[]}>("/transactions?limit=5",{data:[]});return <><PageHeading title="Dashboard" subtitle="Controle seus ganhos e despesas em um só lugar."><div className="heading-actions"><NavLink className="outline" to="/ganhos/novo"><Plus/>Registrar ganho</NavLink><NavLink className="primary" to="/despesas/nova"><Plus/>Registrar despesa</NavLink></div></PageHeading>{summary.error&&<div className="notice error">{summary.error}</div>}<section className="kpis"><Kpi featured label="Saldo atual" value={summary.data.balance} icon={<WalletCards/>}/><Kpi label="Ganhos no período" value={summary.data.income} icon={<ArrowUpRight/>} tone="green"/><Kpi label="Despesas no período" value={summary.data.expense} icon={<ArrowDownLeft/>} tone="red"/></section><section className="charts"><article className="card chart"><CardTitle title="Fluxo financeiro" subtitle="Ganhos e despesas por mês"/><ResponsiveContainer width="100%" height={270}><BarChart data={charts.data.monthly}><CartesianGrid vertical={false} stroke="#eef1f5"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v:number)=>money.format(v)}/><Bar dataKey="income" name="Ganhos" fill="#2161f5" radius={[6,6,0,0]}/><Bar dataKey="expense" name="Despesas" fill="#ff5c6c" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article><article className="card chart"><CardTitle title="Evolução do saldo" subtitle="Saldo acumulado"/><ResponsiveContainer width="100%" height={270}><LineChart data={charts.data.evolution}><CartesianGrid vertical={false} stroke="#eef1f5"/><XAxis dataKey="date" hide/><YAxis hide/><Tooltip formatter={(v:number)=>money.format(v)}/><Line dataKey="balance" stroke="#2161f5" strokeWidth={3} dot={{fill:"#2161f5",r:3}}/></LineChart></ResponsiveContainer></article></section><article className="card recent"><CardTitle title="Movimentações recentes" subtitle="Últimos registros adicionados" action={<NavLink to="/despesas">Ver todas <ArrowRight/></NavLink>}/><TransactionRows data={recent.data.data}/></article></>}
function Kpi({label,value,icon,tone="blue",featured}:{label:string;value:number;icon:React.ReactNode;tone?:string;featured?:boolean}){return <article className={`card kpi ${featured?"featured":""}`}><span className={`kpi-icon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{money.format(value)}</strong>{featured&&<em>Visão consolidada</em>}</div></article>}

function Movements({type,notify}:{type:"income"|"expense";notify:(m:string,e?:boolean)=>void}){const income=type==="income",copy=income?{title:"Ganhos",subtitle:"Registre e acompanhe tudo que entra.",new:"Novo ganho",url:"/ganhos/novo"}:{title:"Despesas",subtitle:"Organize e acompanhe tudo que sai.",new:"Nova despesa",url:"/despesas/nova"};const load=useLoad<{data:Transaction[];summary:{totalIncome:number;totalExpense:number}}>(`/transactions?type=${type}&limit=100`,{data:[],summary:{totalIncome:0,totalExpense:0}});const recurring=useMemo(()=>load.data.data.filter(x=>x.recurring).reduce((s,x)=>s+x.value,0),[load.data.data]);const remove=async(id:string)=>{if(!confirm("Excluir esta movimentação?"))return;try{await api.delete(`/transactions/${id}`);notify("Movimentação excluída.");load.reload()}catch(e){notify(errorMessage(e),true)}};return <><PageHeading title={copy.title} subtitle={copy.subtitle}><NavLink className="primary" to={copy.url}><Plus/>{copy.new}</NavLink></PageHeading><section className="small-kpis"><MiniKpi label="Total no período" value={income?load.data.summary.totalIncome:load.data.summary.totalExpense} icon={<CircleDollarSign/>}/><MiniKpi label="Recorrente mensal" value={recurring} icon={<RefreshCw/>}/><MiniKpi label="Registros" text={String(load.data.data.length)} icon={<Database/>}/></section><article className="card table-card"><CardTitle title={`Lista de ${copy.title.toLowerCase()}`} subtitle="Edite ou remova os registros cadastrados."/>{load.loading?<Empty text="Carregando..."/>:load.error?<Empty text={load.error}/>:<TransactionRows data={load.data.data} actions onDelete={remove}/>}</article></>}
function MiniKpi({label,value,text,icon}:{label:string;value?:number;text?:string;icon:React.ReactNode}){return <article className="card mini-kpi"><span>{icon}</span><div><small>{label}</small><strong>{text??money.format(value||0)}</strong></div></article>}

function TransactionRows({data,actions,onDelete}:{data:Transaction[];actions?:boolean;onDelete?:(id:string)=>void}){if(!data.length)return <Empty text="Nenhuma movimentação cadastrada."/>;return <div className="rows">{data.map(t=><div className="row" key={t.id}><span className={`row-icon ${t.type}`}>{t.type==="income"?<ArrowUpRight/>:<ArrowDownLeft/>}</span><div><b>{t.description}</b><small>{dateBR(t.date)} · {t.userId}{t.recurring?" · Recorrente":""}</small></div><strong className={t.type}>{t.type==="income"?"+":"−"} {money.format(t.value)}</strong>{actions&&<div className="row-actions"><NavLink to={`/movimentacoes/${t.id}`}><Pencil/></NavLink><button onClick={()=>onDelete?.(t.id)}><Trash2/></button></div>}</div>)}</div>}

function MovementForm({type:initialType,notify}:{type?:"income"|"expense";notify:(m:string,e?:boolean)=>void}){
  const{id}=useParams(),navigate=useNavigate(),[loading,setLoading]=useState(Boolean(id));const users=useLoad<AppUser[]>("/users",[]);
  const form=useForm<TransactionInput>({resolver:zodResolver(transactionSchema),mode:"onChange",defaultValues:{userId:"",date:new Date().toISOString().slice(0,10),description:"",value:0,recurring:false,observation:"",type:initialType||"expense",category:"Outros",paymentMethod:"Não informado",status:"paid"}});
  useEffect(()=>{if(id)api.get<Transaction>(`/transactions/${id}`).then(r=>form.reset({...r.data,recurring:Boolean(r.data.recurring)})).catch(e=>notify(errorMessage(e),true)).finally(()=>setLoading(false))},[id]);
  useEffect(()=>{if(!id&&!form.getValues("userId")&&users.data[0])form.setValue("userId",users.data[0].id,{shouldValidate:true})},[users.data,id]);
  const type=form.watch("type");const submit=async(v:TransactionInput)=>{try{id?await api.put(`/transactions/${id}`,v):await api.post("/transactions",v);notify(id?"Movimentação atualizada.":"Movimentação cadastrada.");navigate(type==="income"?"/ganhos":"/despesas")}catch(e){notify(errorMessage(e),true)}};
  return <><PageHeading title={id?"Editar movimentação":type==="income"?"Registrar ganho":"Registrar despesa"} subtitle="Informe os dados essenciais do lançamento."/><article className="card form-card">{loading?<Empty text="Carregando..."/>:<form onSubmit={form.handleSubmit(submit)}><div className="type-switch"><label className={type==="income"?"active income":""}><input type="radio" value="income" {...form.register("type")}/>Ganho</label><label className={type==="expense"?"active expense":""}><input type="radio" value="expense" {...form.register("type")}/>Despesa</label></div><div className="form-grid"><Field label="Título" error={form.formState.errors.description?.message}><input placeholder="Ex.: Salário, aluguel..." {...form.register("description")}/></Field><Field label="Valor" error={form.formState.errors.value?.message}><div className="money-input"><span>R$</span><input type="number" min="0" step="0.01" placeholder="0,00" {...form.register("value")}/></div></Field><Field label="Data"><input type="date" {...form.register("date")}/></Field><Field label="Usuário" error={form.formState.errors.userId?.message}><select {...form.register("userId")}><option value="">Selecione</option>{users.data.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><label className="recurring"><input type="checkbox" {...form.register("recurring")}/><span><b>Movimentação recorrente</b><small>Repetir automaticamente todos os meses.</small></span></label><Field label="Descrição (opcional)" wide><textarea rows={4} placeholder="Observações adicionais" {...form.register("observation")}/></Field></div><div className="form-actions"><button type="button" className="outline" onClick={()=>navigate(-1)}>Cancelar</button><button className="primary" disabled={!form.formState.isValid||form.formState.isSubmitting}>Salvar movimentação</button></div></form>}</article></>}

function Users({notify}:{notify:(m:string,e?:boolean)=>void}){const load=useLoad<AppUser[]>("/users",[]),[name,setName]=useState(""),[email,setEmail]=useState("");const add=async(e:React.FormEvent)=>{e.preventDefault();try{await api.post("/users",{name,email});setName("");setEmail("");load.reload();notify("Usuário adicionado à planilha.")}catch(error){notify(errorMessage(error),true)}};return <><PageHeading title="Usuários" subtitle="Cadastre as pessoas vinculadas às movimentações."/><div className="settings-grid"><article className="card form-card"><CardTitle title="Adicionar usuário" subtitle="O cadastro será gravado na aba Usuarios."/><form onSubmit={add}><div className="form-grid one"><Field label="Nome"><input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="E-mail"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field></div><div className="form-actions"><button className="primary"><Plus/>Adicionar usuário</button></div></form></article><article className="card table-card"><CardTitle title="Usuários cadastrados" subtitle={`${load.data.length} registro(s)`}/>{load.loading?<Empty text="Carregando..."/>:<div className="rows">{load.data.map(u=><div className="row" key={u.id}><span className="row-icon income"><User/></span><div><b>{u.name}</b><small>{u.email||u.id}</small></div><strong>{u.active?"Ativo":"Inativo"}</strong></div>)}</div>}</article></div></>}

type SheetsSettings={workbookId:string;worksheet:string;connected:boolean;configured:boolean;message?:string};
function Configuration({notify}:{notify:(m:string,e?:boolean)=>void}){const load=useLoad<SheetsSettings>("/settings/excel",{workbookId:"",worksheet:"Movimentacoes",connected:false,configured:false}),[testing,setTesting]=useState(false),[result,setResult]=useState<"success"|"error">();const test=async()=>{setTesting(true);setResult(undefined);try{await api.post("/sheets/test");setResult("success");notify("Google Sheets conectado.");load.reload()}catch(e){setResult("error");notify(errorMessage(e),true)}finally{setTesting(false)}};const connected=result==="success"||(result!=="error"&&load.data.connected);return <><PageHeading title="Configurações" subtitle="Verifique a conexão segura com o Google Sheets."/><article className="card connection-card"><span className={connected?"connected":""}>{connected?<CheckCircle2/>:<Database/>}</span><h3>{result==="error"?"❌ Erro de conexão":connected?"✅ Conectado":"Aguardando conexão"}</h3><p>{result==="error"?"Confira o arquivo da Service Account e o compartilhamento da planilha.":load.data.message||"A autenticação é realizada exclusivamente pelo backend."}</p><dl><div><dt>Planilha</dt><dd>{load.data.workbookId||"Não configurada"}</dd></div><div><dt>Abas obrigatórias</dt><dd>Usuarios, Movimentacoes, Listas e Instrucoes</dd></div><div><dt>Autenticação</dt><dd>Service Account no backend</dd></div></dl><div className="form-actions"><button type="button" className="primary" onClick={test} disabled={testing}><RefreshCw/>{testing?"Testando...":"Testar conexão"}</button></div></article></>}

function PageHeading({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}
function CardTitle({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="card-title"><div><h3>{title}</h3><p>{subtitle}</p></div>{action}</div>}
function Field({label,error,children,wide}:{label:string;error?:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?"wide":""}`}><span>{label}</span>{children}{error&&<small className="field-error">{error}</small>}</label>}
function Empty({text}:{text:string}){return <div className="empty"><Database/><span>{text}</span></div>}
