import { google } from "googleapis"; import { randomUUID } from "node:crypto"; import type { Transaction } from "../types/transaction.js"; import { demoTransactions } from "../data/demo.js";
const HEADERS=["ID","Data","Descrição","Categoria","Tipo","Valor","Forma de Pagamento","Status","Observação"];
const configured=()=>Boolean(process.env.GOOGLE_SHEETS_SPREADSHEET_ID&&process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL&&process.env.GOOGLE_PRIVATE_KEY);
const auth=()=>new google.auth.JWT({email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,"\n"),scopes:["https://www.googleapis.com/auth/spreadsheets"]});
const api=()=>google.sheets({version:"v4",auth:auth()}); const id=()=>process.env.GOOGLE_SHEETS_SPREADSHEET_ID!; const range=()=>process.env.GOOGLE_SHEETS_TRANSACTIONS_RANGE||"Movimentacoes!A:I"; const sheet=()=>range().split("!")[0];
const fromRow=(r:string[]):Transaction=>({id:r[0],date:r[1],description:r[2],category:r[3],type:r[4] as Transaction["type"],value:Number(String(r[5]).replace(",",".")),paymentMethod:r[6],status:r[7] as Transaction["status"],observation:r[8]||""});
const row=(t:Transaction)=>[t.id,t.date,t.description,t.category,t.type,t.value,t.paymentMethod,t.status,t.observation||""];
let demo=[...demoTransactions]; export let lastSync:string|null=null;
export async function list(){if(!configured())return [...demo];const res=await api().spreadsheets.values.get({spreadsheetId:id(),range:range()});const rows=res.data.values||[];if(!rows.length)return[];if(HEADERS.some((h,i)=>rows[0]?.[i]!==h))throw new Error("Os cabeçalhos da planilha são inválidos.");lastSync=new Date().toISOString();return rows.slice(1).filter(r=>r[0]).map(fromRow)}
export async function create(input:Omit<Transaction,"id">){const t={...input,id:randomUUID()};if(!configured()){demo.unshift(t);return t}await api().spreadsheets.values.append({spreadsheetId:id(),range:range(),valueInputOption:"USER_ENTERED",requestBody:{values:[row(t)]}});return t}
async function locate(target:string){const all=await list();const idx=all.findIndex(t=>t.id===target);if(idx<0)throw Object.assign(new Error("Movimentação não encontrada."),{status:404});return{all,idx,row:idx+2}}
export async function update(target:string,input:Omit<Transaction,"id">){const found=await locate(target);const t={...input,id:target};if(!configured()){demo[found.idx]=t;return t}await api().spreadsheets.values.update({spreadsheetId:id(),range:`${sheet()}!A${found.row}:I${found.row}`,valueInputOption:"USER_ENTERED",requestBody:{values:[row(t)]}});return t}
export async function remove(target:string){const found=await locate(target);if(!configured()){demo.splice(found.idx,1);return}const meta=await api().spreadsheets.get({spreadsheetId:id()});const s=meta.data.sheets?.find(x=>x.properties?.title===sheet());if(!s)throw new Error("A aba configurada não existe.");await api().spreadsheets.batchUpdate({spreadsheetId:id(),requestBody:{requests:[{deleteDimension:{range:{sheetId:s.properties!.sheetId!,dimension:"ROWS",startIndex:found.row-1,endIndex:found.row}}}]}})}
export async function status(){let count=0,error:string|undefined;if(configured())try{count=(await list()).length}catch(e){error=e instanceof Error?e.message:"Falha na conexão"}else count=demo.length;return{configured:configured(),mode:configured()?"sheets":"demo",spreadsheetId:configured()?process.env.GOOGLE_SHEETS_SPREADSHEET_ID:"",range:range(),serviceAccountEmail:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||"",connected:configured()&&!error,lastSync,records:count,error}}
